# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main", "7.17.18_5.X" ]
  pull_request:
    branches: [ "main", "7.17.18_5.X" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Setup JAVA8_HOME
      run: |
        wget https://cdn.azul.com/zulu/bin/zulu8.76.0.17-ca-jdk8.0.402-linux_x64.tar.gz
        tar xzvf zulu8.76.0.17-ca-jdk8.0.402-linux_x64.tar.gz -C /tmp/

    - name: Build with Gradle Wrapper
      run: |
        export JAVA8_HOME=/tmp/zulu8.76.0.17-ca-jdk8.0.402-linux_x64
        ./gradlew distZip

    - name: Stop gradle daemon
      run: ./gradlew --stop

    - name: Upload build artifact libs
      uses: actions/upload-artifact@v4
      with:
        # default is zip file
        name: ${{ github.sha }}-libs
        path: build/libs
        compression-level: 9

    - name: Upload build artifact dist
      uses: actions/upload-artifact@v4
      with:
        # default is zip file
        name: ${{ github.sha }}-dist
        path: build/distributions
        compression-level: 9
